#%RAML 1.0
types:
  To-Do:
    properties:
      id:
        example: 1
        type: number
        format: int
      title:
        example: Get a Max the Mule plushie at Dreamforce
        type: string
      checked:
        default: false
        example: false
        type: boolean
      dueDate?:
        example: 2023-08-30
        type: date-only
title: My To-Do API
mediaType:
  - application/json
/todos:
  get:
    displayName: Get all To-Dos
    queryParameters:
      titleContains?:
        example: dreamforce
        type: string
      isChecked?:
        default: false
        example: false
        type: boolean
      fromDate?:
        example: 2023-08-30
        type: date-only
      toDate?:
        example: 2023-08-30
        type: date-only
    responses:
      "200":
        body:
          items:
            type: To-Do
  post:
    displayName: Create a To-Do
    body:
      type: To-Do
      example:
        strict: true
        value:
          id: 2
          title: Finish the MuleSoft mini-hack at Dreamforce
          checked: false
          dueDate: 2023-09-14
    responses:
      "201":
        body:
          type: To-Do
          example:
            strict: true
            value:
              id: 2
              title: Finish the MuleSoft mini-hack at Dreamforce
              checked: false
              dueDate: 2023-09-14
/todos/{id}:
  get:
    displayName: Got a To-Do
    responses:
      "200":
        body:
          type: To-Do
  delete:
    displayName: Delete a To-Do
    responses:
      "204": {}
  uriParameters:
    id:
      example: 1
      type: number
      format: int
  post:
    body:
      type: To-Do
    responses:
      "200":
        body:
          type: To-Do
version: 2.0.0
