name: Testing out the GitHub Actions extension

on:
  push:
    branches: [main]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This works yay!"
      - run: echo "My username is ${{ secrets.USERNAME }}"
      - run: echo "My password is ${{ secrets.PASSWORD }}"
